default_platform(:ios)

platform :ios do

  before_all do
		setup_travis
    echo "olá"
    echo ENV["MATCH_KEYCHAIN_NAME"]
    echo ENV["MATCH_KEYCHAIN_PASSWORD"]
		app_store_connect_api_key(key_id: ENV["APPLE_STORE_CONNECT_KEY_ID"],
                              issuer_id: ENV["APPLE_STORE_CONNECT_ISSUER_ID"],
                              key_content: ENV["APPLE_STORE_CONNECT_CONTENT"],
                              in_house: false)
	end

  desc "Run unit tests"
  lane :tests do
    run_tests(workspace: "Compare4Me.xcworkspace", devices: ["iPhone 8"])
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    install_certificates
    increment_build_number
    build_app(workspace: "Compare4Me.xcworkspace", scheme: "Compare4Me")
    upload_to_testflight
  end

  desc "Installs the certificates locally"
  private_lane :install_certificates do
    keychain_name = ENV["MATCH_KEYCHAIN_NAME"]
    keychain_password = ENV["MATCH_KEYCHAIN_PASSWORD"]

    create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: true,
      timeout: 3600,
      unlock: true,
    )
    match(
      type: "appstore",
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      readonly: true
    )
  end
end
