name: Release

on:
  push:
    branches: [ release ]

jobs:
  beta:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "12.4"
        
    - name: Bundle
      run: bundle install
      
    - name: Dependencies
      run: bundle exec pod install
      
    - name: Beta
      run: bundle exec fastlane beta
      env:
        MATCH_PASSWORD: "${{ secrets.MATCH_PASSWORD }}"
        APPLE_STORE_CONNECT_ISSUER_ID: "${{ secrets.APPLE_STORE_CONNECT_ISSUER_ID }}"
        APPLE_STORE_CONNECT_KEY_ID: "${{ secrets.APPLE_STORE_CONNECT_KEY_ID }}"
        APPLE_STORE_CONNECT_CONTENT: "${{ secrets.APPLE_STORE_CONNECT_CONTENT }}"
        GIT_AUTHORIZATION: "${{ secrets.GIT_AUTHORIZATION }}"
